# Jason Booth   Project 5b   boo-5b
# -Wno-deprecated is used to remove the error message associated with the
# d_except.h file using a deprecated library

executable: maze.h graphOperations.h d_except.h d_matrix.h
	g++ -std=c++11 main.cpp -Wno-deprecated -o executable

clean:
	rm *.o executable