# Jason Booth   Project 5c   boo-5c
# -Wno-deprecated is used to remove the error message associated with the
# d_except.h file using a deprecated library

executable: graphProcedures.h d_except.h
	g++ -std=c++11 main.cpp -Wno-deprecated -o executable

clean:
	rm *.o executable
