# Jason Booth   Project 6b  boo-6b
# -Wno-deprecated is used to remove the error message associated with the
# d_except.h file using a deprecated library

executable: graphOperations.h d_except.h
	g++ -std=c++11 main.cpp -Wno-deprecated -o executable

clean:
	rm *.o executable
